services:
  - type: web
    name: content-locker
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: content-locker-db
          property: connectionString

databases:
  - name: content-locker-db
    plan: free